spring.application.name=backend
spring.datasource.url=jdbc:mysql://10.0.2.2:3307/tp3_db
spring.datasource.username=tp3_user
spring.datasource.password=Tp3Pass123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Allow cross-origin requests for the frontend during development if needed
# (though Nginx reverse proxy handles it in prod)
